### ISSUE TITLE
problem in fluidd with dynamic_macros

### ISSUE THREAD

**Issue by Kastillo75** [3DCoded/DynamicMacros#14]
Hello, I'm writing here because I don't know where to do it and no matter how much I search, I can't find any information about the problem I have with dynamic macros.
In mainsail I see them correctly, but in fluidd, which is what I use the most, I have the problem that no macro appears, I don't see any, I have it like this in printer.cfg:
[dynamicmacros]
configs: dynamic.cfg
interface_workaround: true.
I have created dynamic.cfg within config with the macros inside and nothing, if I go into the configuration options of fluidd/ macros, there are some I see like pid tunig, printer control and some more and mine are about 37 that I have uncategorized but I only see the name of the category and if I open them a black page appears, and in the fluid interface I don't see any, I have an elegoo neptune 4 max and I have it installed OpenNept4tune and I don't know if that will be the problem, is there some kind of solution because I've been trying to solve it for a week, thank you and sorry if the question doesn't belong here, greetings

**Comment by 3DCoded** [comment]
Hi @Kastillo75 ,

Could you please upload your printer config folder, so I can investigate this issue further?

**Comment by Kastillo75** [comment]
Hello, I send you here the printer.cfg, the dynamoc.cfg and a photo of mainsail where the macros do appear, and a video where you can see that the macros do not appear in fluidd and for my bad luck fluidd is the interface that I usually use now Which I like more than Mainsail because of its order. Greetings and anything you want to know or ask I will try to answer you as quickly as possible.


https://github.com/user-attachments/assets/aeda3946-b0ea-4e99-b24c-a2d971ebaa66
[printer.cfg_and_dynamic.cfg.zip](https://github.com/user-attachments/files/18269320/printer.cfg_and_dynamic.cfg.zip)
![IMG_20241228_113255_710](https://github.com/user-attachments/assets/f0d4f9d1-b195-4afb-905c-d93cc014a6b9)

**Comment by 3DCoded** [comment]
Hi,

Thank you for uploading the config files. Dynamic Macros generates a hidden file named `.dynamicmacros.cfg`. Could you please upload this? 

Also, do the macros appear if you remove all `delayed_gcode` entries from `dynamic.cfg`? You may need to restart Klipper a few times after this change.

**Comment by 3DCoded** [comment]
Hi @Kastillo75 ,

I have pushed a fix in the `dev` branch that has allowed `delayed_gcode`s to be present and still display in Fluidd. Can you please verify this works on your Fluidd?

```
cd ~/DynamicMacros
git checkout dev
git pull
sh install.sh
sudo service klipper restart
```

**Comment by Kastillo75** [comment]
Hello, I sent you the .dynamicmacros.cfg and now I will try the fix dev that you have created and tell you if it works
[dynamicmacros.zip](https://github.com/user-attachments/files/18270269/dynamicmacros.zip)

**Comment by Kastillo75** [comment]
wow perfect with your correction now I see all the macros, you are fantastic, thank you for your speed, greetings and thank you very much for everything, now I can continue enjoying the printer,,,,

**Comment by Kastillo75** [comment]
oopsss when I restarted the printer the macros are lost again, is there a way to make this arrangement consistent

**Comment by 3DCoded** [comment]
Hi @Kastillo75 ,

The way the interface workaround works is:

1. On restart, the `.dynamicmacros.cfg` is created/updated with the dynamic macros. These are placeholders to trick Fluidd/KlipperScreen into displaying the macro
2. On the second restart, Klipper loads `.dynamicmacros.cfg`. Unfortunately, there isn't a way to make Klipper load the new file (yet) without restarting

Can you verify if this works after the second restart?

**Comment by Kastillo75** [comment]
No, if I turn off or restart the printer or refresh the fluidd interface in the browser, I have to run again:
cd ~/DynamicMacros
git checkout dev
git pull
sh install.sh
sudo service clipper restart
and then the macros are displayed again after restarting these commands

**Comment by 3DCoded** [comment]
I am able to reproduce this by restarting the Pi. I'll look into this...

**Comment by Kastillo75** [comment]
ok thanks

**Comment by 3DCoded** [comment]
I think I found the issue (related to `initial_duration`). The latest push should ignore the parameter. Please let me know if this works on your Fluidd.

**Comment by Kastillo75** [comment]
cd ~/DynamicMacros
git checkout dev
git pull
sh install.sh
sudo service clipper restart
and then the macros are displayed again after restarting these commands
you mean this?
When I turned it on it still didn't work, I had to write it via ssh and then it would work
I put this in printer.cfg with a brief restart of klipper and then if I see the macros
[delayed_gcode RESTART_KLIPPER]
initial_duration: 2
gcode:
    {% if not printer.gcode.query_file("/home/mks/.klipper_restarted") %}
        RESPOND PREFIX="info" MSG="Reiniciando Klipper en 2 segundos..."
        SYSTEM "touch /home/mks/.klipper_restarted"  # Crear archivo de control
        FIRMWARE_RESTART
    {% else %}
        SYSTEM "rm /home/mks/.klipper_restarted"  # Eliminar archivo de control después del reinicio
        RESPOND PREFIX="info" MSG="Reinicio completado, archivo eliminado."
    {% endif %}
The only problem I have left would be to refresh the fluidd interface in the browser, apparently moonraiker is refreshed but not fluidd, and I lose the macros again, is there a way to restart klipper when I refresh the fluidd page, I'm trying with a java script but I have no way to make it work

**Comment by 3DCoded** [comment]
If you reload Fluidd, Klipper and Moonraker don’t restart. If it did, your print would fail every time you refreshed the page.

**Comment by 3DCoded** [comment]
Also, after running the commands and restarting Klipper up to two times, the macros should always be present in Fluidd.

**Comment by Kastillo75** [comment]
Thanks, I just got home from work and I tried restarting twice, it seems to work fine, when I refresh the page the macros remain, but the problem I have now is that if I run DYNAMIC_MACRO, the macros disappear and I have to restart Klipper again for them to appear,,, sorry for the inconvenience.

**Comment by 3DCoded** [comment]
Hi @Kastillo75 ,

Sorry for all the issues! I have pushed a patch for this in the `dev` branch. Please let me know if this works on your setup.

**Comment by Kastillo75** [comment]
I still have the same problem, I'm really sorry for the inconvenience I'm causing you.
Let me explain in more detail, if I create a new macro and run DYNAMIC_MACRO, the new macro doesn't load, I have to refresh fluidd and then I lose the macros again, I've already run the latest dev fix and restarted twice but nothing, I lose them when I create a new macro, maybe I'm wrong but is it not supposed to be like that right? or is that still being implemented?

**Comment by 3DCoded** [comment]
Unfortunately, the way Fluidd works, it will only recognize macros existing on Klipper startup. If a new macro suddenly appears, it doesn't know what to do and doesn't display any macros. Adding macros without restarting Klipper is a core feature of DynamicMacros, but it seems Fluidd doesn't support it...

**Comment by Kastillo75** [comment]
Ok thanks, mainsail does not accept new macros without restarting either, great work on your part, thank you very much for the effort, time and patience you have had.

**Comment by Kastillo75** [comment]
Perfect, I'll be on the lookout in case a solution or modification arises, since what you have developed seems to me to be a very interesting option. Regards.

**Comment by Kastillo75** [comment]
Hello, I have detected a new problem, if I make a print everything is fine, but if I make a second print of the same or a different object without restarting the printer I always get this error MCU 'mcu' shutdown: Stepper too far in past
This generally occurs when the micro-controller has been
requested to step at a rate higher than it is capable of
obtaining.
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown,
 I have been trying to solve it for three days but I have no way, it has been happening to me since I started using dynamic_macros. I'll put the start_print macros and the purge line macro to see if you are able to see where the error is, thank you very much
[gcode_macro PRINT_START_NO_KAMP_PRUEBAS]
gcode:
    RESPOND PREFIX="⚠️" MSG="COMENZANDO IMPRESION ⚠️"
    Frame_Light_ON
    Part_Light_ON
    CG28
    G90                       ; Use absolute coordinates
    ;BED_MESH_CLEAR    

    ; Establecer variables dinámicas
    SET_DYNAMIC_VARIABLE MACRO=PRINT_START_NO_KAMP_PRUEBAS VARIABLE=BED_TEMP VALUE={params.BED_TEMP|default(60)|float}  ; Temperatura de la cama
    SET_DYNAMIC_VARIABLE MACRO=PRINT_START_NO_KAMP_PRUEBAS VARIABLE=EXTRUDER_TEMP VALUE={params.EXTRUDER_TEMP|default(200)|float}  ; Temperatura del extrusor
    SET_DYNAMIC_VARIABLE MACRO=PRINT_START_NO_KAMP_PRUEBAS VARIABLE=BED_HEAT_SOAK_MINUTES VALUE={params.BED_HEAT_SOAK_MINUTES|default(0)|float}  ; Tiempo de espera para estabilizar la cama
    ; Mostrar los valores de las variables
    
    ; Confirmar los valores de las variables
    RESPOND PREFIX="⚠️" MSG="Cama: {BED_TEMP}°C, Extrusor: {EXTRUDER_TEMP}°C ⚠️ ."

    ; Calentar la cama
    SET_BED_TEMPERATURE TARGET={BED_TEMP}                           ; Calentar la cama a la temperatura objetivo
    BED_TEMPERATURE_WAIT MINIMUM={BED_TEMP-2} MAXIMUM={BED_TEMP+4}  ; Esperar hasta que la cama esté cerca de la temperatura objetivo

    {% if BED_HEAT_SOAK_MINUTES > 0 %}
    RESPOND MSG="Esperando {BED_HEAT_SOAK_MINUTES} minutos para estabilizar la cama."
    G4 P{BED_HEAT_SOAK_MINUTES * 60000}  ; Esperar el tiempo de estabilización de la cama
    {% endif %}

    RESPOND PREFIX="⚠️" MSG="POSICIONANDO ⚠️"
    Smart_Park     
    RESPOND PREFIX="⚠️" MSG="calentando extrusor ⚠️"
    SET_FILAMENT_SENSOR SENSOR=filament_sensor ENABLE=1              ; Activar el sensor de filamento
    M109 S{EXTRUDER_TEMP}                                            ; Establecer y esperar a que el extrusor alcance la temperatura objetivo
    RESPOND PREFIX="⚠️" MSG="LINEA PURGA ⚠️"                        ; Realizar la línea de purga
    SMART_LINE_PURGE                                           
    G92 E0                                                           ; Resetear el extrusor
    G1 Z2.0 F3000                                                    ; Mover el eje Z hacia arriba
    ;M117 Printing                                                   ; Mostrar mensaje "Printing"
  

   [gcode_macro SMART_LINE_PURGE]
description: Purge line starting from SMART_PARK with specified path and cleanup
gcode:
   # CONFIGURACIÓN DE VARIABLES DINÁMICAS
    SET_DYNAMIC_VARIABLE MACRO=SMART_LINE_PURGE VARIABLE=purge_length VALUE=50         ; Longitud de la línea de purga en mm
    SET_DYNAMIC_VARIABLE MACRO=SMART_LINE_PURGE VARIABLE=purge_extrusion VALUE=5       ; Extrusión para la línea de purga en mm
    SET_DYNAMIC_VARIABLE MACRO=SMART_LINE_PURGE VARIABLE=travel_speed VALUE=3000       ; Velocidad de desplazamiento en mm/min
    SET_DYNAMIC_VARIABLE MACRO=SMART_LINE_PURGE VARIABLE=lift_height VALUE=3           ; Altura de elevación para el nozzle en mm
    SET_DYNAMIC_VARIABLE MACRO=SMART_LINE_PURGE VARIABLE=purge_height VALUE=0.2        ; Altura de la primera capa

    ; Mostrar los valores de las variables utilizando RESPOND
    RESPOND PREFIX="SMART_LINE_PURGE" MSG="Longitud de la línea de purga: {purge_length} mm"
    RESPOND PREFIX="SMART_LINE_PURGE" MSG="Extrusión para la línea de purga: {purge_extrusion} mm"
    RESPOND PREFIX="SMART_LINE_PURGE" MSG="Velocidad de desplazamiento: {travel_speed} mm/min"
    RESPOND PREFIX="SMART_LINE_PURGE" MSG="Altura de elevación del nozzle: {lift_height} mm"
    RESPOND PREFIX="SMART_LINE_PURGE" MSG="Altura de la primera capa: {purge_height} mm"

    # GUARDAR POSICIÓN ACTUAL
    G90  ; Asegura que estamos en coordenadas absolutas antes de guardar
    SET_DYNAMIC_VARIABLE MACRO=SMART_LINE_PURGE VARIABLE=position_x VALUE={printer.toolhead.position.x}
    SET_DYNAMIC_VARIABLE MACRO=SMART_LINE_PURGE VARIABLE=position_y VALUE={printer.toolhead.position.y}
    SET_DYNAMIC_VARIABLE MACRO=SMART_LINE_PURGE VARIABLE=position_z VALUE={printer.toolhead.position.z}

    ; Mostrar las coordenadas guardadas
    RESPOND PREFIX="Head_Position" MSG="Posición guardada: X={position_x}, Y={position_y}, Z={position_z}"

    # Movimientos para realizar la purga
    G91  ; Cambiar a coordenadas relativas para los movimientos de purga

    G0 Y-1 ; Baja 1mm para purga
    LINE_PURGE
    G0 Y-1 ; Baja otro 1mm
    G1 Z0.2 F1000  ; Mueve a la altura de la primera capa
    G1 X-{purge_length} E{purge_extrusion} F500 ; Extrusión hacia atrás

    ;G90  ; Regresa a coordenadas absolutas después de la purga
    G0 Z3 F{travel_speed}  ; Subir el nozzle
    G92 E0  ; Reiniciar extrusor

    # MOVIMIENTOS RÁPIDOS DE LIMPIEZA
    G0 X{purge_length} F30000 ; Mover rápido a la derecha
    G0 X-{purge_length} F30000 ; Mover rápido a la izquierda

    G0 X{purge_length} F30000 ; Mover rápido a la derecha
    G0 X-{purge_length} F30000 ; Mover rápido a la izquierda
    G0 X-10 F30000  ; Mover 10 mm más a la izquierda

    # VUELVE A LA POSICIÓN GUARDADA
    G90  ; Asegúrate de que estamos usando coordenadas absolutas
    G0 X{position_x} Y{position_y} Z{position_z}  ; Mover a la posición guardada

**Comment by 3DCoded** [comment]
Hi @Kastillo75 ,

DynamicMacros doesn't interact at all with the stepper part of Klipper. My best guess would be that your Klipper host is under a high CPU load from a webcam or other program. 

What Klipper host are you using?
What mainboard are you using?
What microsteps are you using?
How fast are you running your steppers?

**Comment by Kastillo75** [comment]
and I have an aelegoo neptune 4 max with opennept4une installed, it has klikpper built in, the strange thing is that as I told you, I turn on the printer and print a piece, when it finishes without touching anything else and printing the same piece again is when it throws the error.
Update I have already discovered the error, as you can see in my macro that I put [gcode_macro SMART_LINE_PURGE] I use the KAMP macro LINE_PURGE, this is the one that generates the error in the second print, could it be because it is not a dynamic_macro? I have included it in the macro and now it does not give the error, but what I do not know is how to solve it since I want it to do LINE_PURGE and then the rest of the movements, should LINE_PURGUE be done as if it were a dynamic macro in its definition? .. greetings and many thanks

**Comment by 3DCoded** [comment]
Hi @Kastillo75 ,

It shouldn't matter if your `LINE_PURGE` macro is dynamic or not. I use the non-dynamic `LINE_PURGE` KAMP macro in my dynamic `PRINT_START` macro and it works fine.

**Comment by tistructor** [comment]
I solved the problem by adding this string to the printer.cfg file

`
[include dynamic.cfg]
`

**Comment by 3DCoded** [comment]
@Kastillo75 
@tistructor 

This is now fixed as of the latest release of Fluidd!

**Comment by tistructor** [comment]
Does the installation file now also work for K1 Max?
Don't need a custom version for K1 Max anymore?

**Comment by tistructor** [comment]
Thanks.

I've read the release notes and can't determine the klipper version of my K1 Max.

How do you read the version?

**Comment by tistructor** [comment]
I found the version.

09faed31-dirty 

Can it work with the new version of Dynamic Macros?

**Comment by 3DCoded** [comment]
@tistructor ,

Unfortunately, the version doesn't help. If you can get the K1 Max running on mainline Klipper, you can use DynamicMacros.

This might help:
https://github.com/ballaswag/creality_k1_klipper_mod
